### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by dknutsen** [EmberMap/acceptance-testing-training#1]
I'm running into a build issue with both node v6.10.1 and v7.4.0:
```
acceptance-testing-training dknutsen$ ember build
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/tmp/source_map_concat-input_base_path-ZVGdMWZ4.tmp/bower_components/blueimp-md5/js/md5.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at SourceMap.addFile (/Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/dknutsen/workspace/emberconf/2017/acceptance-testing-training/node_modules/rsvp/dist/rsvp.js:1077:33)
```

It seems like it could be related to ember-cli-gravatar:
```
ember-cli-gravatar/index.js
15:    app.import(app.bowerDirectory + '/blueimp-md5/js/md5.js');
```

**Comment by dknutsen** [comment]
Worked if I added blueimp-md5 to bower.json and did a `bower install` before building (see below). Seems like ember-cli-gravatar isn't correctly downloading/installing this dependency? Hope this helps if anyone else runs into this.

```
{
  "name": "acceptance-testing-training",
  "dependencies": {
    "blueimp-md5": "~2.3.0"
  }
}
```
